import '@/app/globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import { Toaster } from '@/components/ui/toaster'
import ReduxProviderWrapper from '@/lib/redux/ReduxProviderWrapper'
import IconCorpLogo from '@/components/svg/IconCorpLogo'

export async function generateStaticParams() {
   return [{ lang: 'es-ES' }]
}
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function LoginLayout({ children }) {
   ////console.log('Props /bookin/layout -> ', props)
   return (
      <html lang="es-ES" dir="ltr" className="h-full bg-red-500">
         <body className="h-full">
            <ReduxProviderWrapper>
               <div className="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8">
                  <div className="sm:mx-auto sm:w-full sm:max-w-md">
                     <IconCorpLogo className={'h-[200px] w-[200px] '} />
                  </div>

                  {children}
               </div>
               <Toaster />
            </ReduxProviderWrapper>
         </body>
      </html>
   )
}
