import './admin.css'
import { Inter } from 'next/font/google'
import React, { Suspense } from 'react'
import ReduxProviderWrapper from '@/lib/redux/ReduxProviderWrapper'
import { BookingBreadcrumb } from './dashboard/bookings/BookingBreadcrumb'
import AdminBar from './AdminBar'
import AdminSidebar from './AdminSidebar'
import AdminMainContainer from './AdminMainContainer'
import { ProgressBar, ProgressBarProvider } from 'react-transition-progress'

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import { GlobalDialogLoader } from '@/components/common/GlobalDialogLoader'
import theme from '@/theme'
import DashBoardLayout from '@/components/mui/layouts/DashBoardLayout'

export async function generateStaticParams() {
   return [{ lang: 'es-ES' }]
}
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}
//https://github.com/vercel/next.js/discussions/41934#discussioncomment-8996669
export default function AdminDashboardLayout(props) {
   // console.log('Props /bookin/layout -> ', props.params)
   return (
      <html lang="es-ES" dir="ltr">
         <body>
            <AppRouterCacheProvider>
               <ThemeProvider theme={theme}>
                  <ReduxProviderWrapper>
                     <GlobalDialogLoader />
                     <ProgressBarProvider>
                        <ProgressBar className="aaf fixed top-0 z-50 h-2 w-full bg-white shadow-lg shadow-sky-500/20" />
                        <DashBoardLayout>{props.children}</DashBoardLayout>
                     </ProgressBarProvider>
                  </ReduxProviderWrapper>
               </ThemeProvider>
            </AppRouterCacheProvider>
         </body>
      </html>
   )
}
