import DashboardLayout from '@/components/layout/DashboardLayout'
import './globals.css'
import { Inter } from 'next/font/google'
import React from 'react'

export async function generateStaticParams() {
   return [{ lang: 'es-ES' }]
}
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({ children, params }) {
   console.log('Params -> ', params)
   return (
      <html lang="es-ES" dir="ltr" className="h-full bg-red-500">
         <body className="h-full">
            <DashboardLayout>{children}</DashboardLayout>
         </body>
      </html>
   )
}
