import '@/app/globals.css'
import { Inter } from 'next/font/google'
import React from 'react'
import SiteShell from '@/components/layouts/site/SiteShell'
import ReduxProviderWrapper from '@/lib/redux/ReduxProviderWrapper'
import { Toaster } from '@/components/ui/toaster'

export async function generateStaticParams() {
   return [{ lang: 'es-ES' }]
}
export const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function SiteLayout(props) {
   return (
      <html lang="es-ES" dir="ltr" className="h-full bg-green-500">
         <body>
            <ReduxProviderWrapper>
               <SiteShell {...props} />
               <Toaster />
            </ReduxProviderWrapper>
         </body>
      </html>
   )
}
